
USE BI_SellInSellOut
--============================================================================================
--=======================	CRIANDO TABLEA DIMENSÃO DA TABELA FATO TB_CATEGORIA	=======================

--CRIANDO TABELA DIMENSÃO DIM_CATEGORIA_ PRODUTO DA TB_CATEGORIA
SELECT	*
FROM	TB_CATEGORIA;

SELECT DISTINCT PRODUTO
FROM			TB_CATEGORIA;

CREATE TABLE DIM_CATEGORIA_PRODUTO (
	ID_PRODUTO	INT IDENTITY(1,1)	PRIMARY KEY,
	PRODUTO		NVARCHAR(100),
	SKU			NVARCHAR(50)	
);
INSERT INTO		DIM_CATEGORIA_PRODUTO (PRODUTO, SKU)
SELECT DISTINCT PRODUTO, SKU
FROM			TB_CATEGORIA;

SELECT *
FROM	DIM_CATEGORIA_PRODUTO;

--CRIANDO TABELA DIMENSÃO DIM_CATEGORIA_CANAL DA TB_CATEGORIA

SELECT	*
FROM	TB_CATEGORIA;

SELECT DISTINCT CANAL
FROM			TB_CATEGORIA;

CREATE TABLE DIM_CATEGORIA_CANAL (
	ID_CANAL	INT IDENTITY(1,1)	PRIMARY KEY,
	CANAL		NVARCHAR(100)
);
INSERT INTO		DIM_CATEGORIA_CANAL
SELECT DISTINCT	CANAL
FROM			TB_CATEGORIA;

SELECT	*
FROM	DIM_CATEGORIA_CANAL;

--CRIANDO TABELA DIMENSÃO DIM_CATEGORIA_REGIAO DA TB_CATEGORIA
SELECT	*
FROM	TB_CATEGORIA;

SELECT DISTINCT REGIÃO
FROM			TB_CATEGORIA;

CREATE TABLE	DIM_CATEGORIA_REGIAO (
	ID_REGIAO		INT IDENTITY(1,1)	PRIMARY KEY,
	REGIAO	NVARCHAR(100)
);
INSERT INTO		DIM_CATEGORIA_REGIAO
SELECT DISTINCT REGIÃO
FROM			TB_CATEGORIA;

SELECT	*
FROM	DIM_CATEGORIA_REGIAO;

--============================================================================================
--=======================	CRIANDO JOIN TABLEA DIMENSÃO COM TABELA FATO TB_CATEGORIA	=======================

--JOIN DIM_CATEGORIA_PRODUTO
SELECT	p.ID_PRODUTO, p.PRODUTO, p.SKU, f.QUANTIDADE, f.VALOR
FROM	TB_CATEGORIA f
JOIN	DIM_CATEGORIA_PRODUTO p
ON		f.PRODUTO = p.PRODUTO
AND		f.SKU = p.SKU;

--JOIN DIM_CATEGORIA_CANAL
SELECT	c.ID_CANAL, c.CANAL, f.QUANTIDADE, f.VALOR 
FROM	TB_CATEGORIA f
JOIN	DIM_CATEGORIA_CANAL c
ON		f.CANAL = c.CANAL;

--JOIN DIM_CATEGORIA_REGIAO
SELECT	r.ID_REGIAO, r.REGIAO, f.QUANTIDADE, f.VALOR
FROM	TB_CATEGORIA f
JOIN	DIM_CATEGORIA_REGIAO r
ON		f.[Região] = r.REGIAO;

--JOIN ENTRE TODAS AS DIM
GO
CREATE VIEW VW_CATEGORIA AS
SELECT
		f.QUANTIDADE,
		f.VALOR,
		p.ID_PRODUTO,
		p.PRODUTO,
		p.SKU,
		c.ID_CANAL,
		c.CANAL,
		r.ID_REGIAO,
		r.REGIAO,
		dt.DATA,
		dt.ANO,
		dt.NOME_MES,
		dt.TRIMESTRE,
		dt.DIA,
		dt.DIA_SEMANA
FROM	TB_CATEGORIA f
-- PRODUTO
JOIN	DIM_CATEGORIA_PRODUTO p
ON		f.PRODUTO = p.PRODUTO
AND		f.SKU = p.SKU
-- CANAL
JOIN	DIM_CATEGORIA_CANAL c
ON		f.CANAL = c.CANAL
-- REGIAO
JOIN	DIM_CATEGORIA_REGIAO r
ON		f.[Região] = r.REGIAO
-- DATA
JOIN	DIM_DATAS dt
ON		f.DATA = dt.DATA

SELECT	*
FROM	TB_CATEGORIA;