
--=======================	DASHBOARD SELL-IN SELL-OUT	=======================

--CRIANDO DATABASE
CREATE DATABASE BI_SellInSellOut

--SETANDO O USO DO DATABASE
USE	BI_SellInSellOut

--=======================	TABELAS FATOS FORAM INSERIDAS DIRETO NO DATABASE A PARTIR DO ARQUIVO CSV DO EXCEL	=======================

--============================================================================================
--=======================	CRIANDO TABELAS DIMENSÕES	=======================

--DIMENSÃO PRODUTOS
SELECT *
FROM	TB_VENDAS;

SELECT DISTINCT(PRODUTO)
FROM	TB_VENDAS;

CREATE TABLE DIM_PRODUTOS (
	ID_PRODUTO	INT	IDENTITY(1,1)	PRIMARY KEY,
	PRODUTO		NVARCHAR(100),
	SKU			NVARCHAR(50)
);
INSERT	INTO		DIM_PRODUTOS	(PRODUTO, SKU)
SELECT	DISTINCT	PRODUTO, SKU
FROM				TB_VENDAS;

SELECT *
FROM	DIM_PRODUTOS;

--DIMENSÃO DISTRIBUIDOR

SELECT *
FROM	TB_VENDAS;

SELECT DISTINCT	DISTRIBUIDOR
FROM	TB_VENDAS;

CREATE TABLE DIM_DISTRIBUIDOR (
	ID_DISTRIBUIDOR		INT IDENTITY(1,1)	PRIMARY KEY,
	DISTRIBUIDOR		NVARCHAR(100)
);
INSERT INTO		DIM_DISTRIBUIDOR (DISTRIBUIDOR)
SELECT DISTINCT	DISTRIBUIDOR
FROM			TB_VENDAS;

SELECT *
FROM	DIM_DISTRIBUIDOR;


--DIMENSÃO REGIÃO
SELECT *
FROM TB_VENDAS;

SELECT DISTINCT REGIÃO
FROM			TB_VENDAS;

CREATE TABLE DIM_REGIAO (
	ID_REGIAO	INT	IDENTITY(1,1)	PRIMARY KEY,
	REGIAO		NVARCHAR(100)
);
INSERT INTO		DIM_REGIAO	(REGIAO)
SELECT DISTINCT REGIÃO
FROM			TB_VENDAS;

SELECT *
FROM	DIM_REGIAO;

--TABELA DIMENSÃO CALENDÁRIO

CREATE TABLE DIM_DATAS (
	ID_DATA		INT	IDENTITY(1,1)	PRIMARY KEY,
	DATA		DATE,
	ANO			INT,
	MES			INT,
	NOME_MES	NVARCHAR(20),
	TRIMESTRE	INT,
	DIA			INT,
	DIA_SEMANA	NVARCHAR(20)
);
WITH CTE AS (
	SELECT CAST('2023-01-01' AS DATE) AS DATA
	UNION ALL
	SELECT DATEADD(DAY, 1, DATA)
	FROM CTE
	WHERE DATA < '2025-12-31'
)
INSERT INTO DIM_DATAS (DATA, ANO, MES, NOME_MES, TRIMESTRE, DIA, DIA_SEMANA)
SELECT
	DATA,
	YEAR(DATA)				AS ANO,
	MONTH(DATA)				AS MES,
	DATENAME(MONTH, DATA)	AS NOME_MES,
	DATEPART(QUARTER, DATA)	AS TRIMESTRE,
	DAY(DATA)				AS DIA,
	DATENAME(WEEKDAY, DATA)	AS DIA_SEMANA
FROM CTE
OPTION (MAXRECURSION 1096);

SELECT *
FROM DIM_DATAS;

--============================================================================================
--=======================	CRIANDO JOIN TABLEA DIMENSÃO COM TABELA FATO DA TB_VENDAS	=======================

--JOIN DIM_PRODUTOS
SELECT	f.QUANTIDADE, f.VALOR, p.PRODUTO, p.SKU
FROM	TB_VENDAS f
JOIN	DIM_PRODUTOS p
ON		f.PRODUTO = p.PRODUTO
AND		f.SKU = p.SKU;

--JOIN DIM_DISTRIBUIDOR
SELECT	f.QUANTIDADE, f.VALOR, d.DISTRIBUIDOR
FROM	TB_VENDAS f
JOIN	DIM_DISTRIBUIDOR d
ON		f.DISTRIBUIDOR = d.DISTRIBUIDOR;

--JOIN DIM_REGIÃO
SELECT	f.QUANTIDADE, f.VALOR, r.REGIAO
FROM	TB_VENDAS f
JOIN	DIM_REGIAO r
ON		f.[Região] = r.REGIAO;

--JOIN DIM_DATA
SELECT	f.QUANTIDADE, f.VALOR, dt.ANO, dt.NOME_MES, dt.DIA_SEMANA
FROM	TB_VENDAS f
JOIN	DIM_DATAS dt
ON		f.DATA = dt.DATA;

--JOIN ENTRE TODAS AS DIM
SELECT 
    f.QUANTIDADE,
    f.VALOR,
	p.ID_PRODUTO,
    p.PRODUTO,
    p.SKU,
	d.ID_DISTRIBUIDOR,
    d.DISTRIBUIDOR,
	r.ID_REGIAO,
    r.REGIAO,
	dt.ID_DATA,
    dt.ANO,
    dt.NOME_MES,
    dt.TRIMESTRE,
    dt.DIA_SEMANA
FROM TB_VENDAS f
JOIN DIM_PRODUTOS p
    ON f.PRODUTO = p.PRODUTO
   AND f.SKU = p.SKU
JOIN DIM_DISTRIBUIDOR d
    ON f.DISTRIBUIDOR = d.DISTRIBUIDOR
JOIN DIM_REGIAO r
    ON f.[Região] = r.REGIAO  
JOIN DIM_DATAS dt
    ON f.DATA = dt.DATA;
